import '../classes/project.dart';

class ProjectDetails {
  List<Project> projectList = [
    Project(
      projectName: 'Dunder Mifflin',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'A pennsylvania based paper company',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'Nike',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'The tick shoe company',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'Fortnite',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'Dont play this game',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'BLah blah',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'it Do be like that sometimes but all the times yet none of the times yet most of the times altough it is like that but not so much',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'Fight Club',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'An underground boxing league for under privileged kids',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'El Gato',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'The kitty cafe in downtown atlantis',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'Shawarma G',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'Not shawarmas but somthing like shawarmas',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
    Project(
      projectName: 'Dunder Mifflin',
      projectImage: 'https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png',
      projectDescription: 'A pennsylvania based paper company',
      projectClient: 'Client',
      projectComments: 'Very good!',
      projectLabels: 'Bad very_bad',
      projectTasks: 'task A',
    ),
  ];
}